### ISSUE TITLE
Upload to Garmin Connect not working

### ISSUE THREAD

**Issue by Lay3r3ight** [danips/ANTWeightScaleDisplay#1]
Hello Daniel,

I am a customer of you ANT+ Weight Scale app and I am happy to see that you made it open source. 

I noticed that you unpublished the app 2022 from playstore but updated it after this event to v3.17. Thanks for this maintenance release.

The app is still working on Android 13 phones (Samsung S20 Plus of my wife with integrated ANT+) and it also worked for quiet a while with my Android 14 (my Samsung S23 Ultra with the ANT+ USB dongle). Its currently not longer working on my S23U since Samsung or ANT+ released an update for the phone or the ANT+ Services.

Sadly the upload on the S20+ is not working since some weeks or months again. It looks like Garmin changed something on their website or the login procedure. In the past I entered Username / Passwort in the app as account credentials for garmin connect and I also saved this combination in my password manager. But it looks like garmin changed it to email / password credentials combination and maybe some other characteristics on the website changed too, so the app cant no longer login to Garmin connect.

I would kindly ask if you could please fix this Garmin connect login issue again?

Also, I would kindly ask if you could remove the licence check because its not longer possible to buy the app in the play store. At the moment, the app is only working in demo mode on my wifes S20+. But she is using the playstore version 3.17, not sure if the github version 3.17 is diffent.

Kind regards

**Comment by danips** [comment]
Sorry for the late reply.
I removed the app from Google Play because I knew Garmin would eventually break uploads, and I couldn't guarantee to be able to fix it. It finally happened back in October. I tried to fix Garmin Uploads several months ago, but I ended up giving up.
I just kept waiting for another person's fix. This happened recently: https://github.com/kochka/WeightLogger/issues/68#issuecomment-1956190451
I've been trying it myself for the last 24 hours and it seems to be working. Keep in mind there seems to be very low rate limits. I was manually uploading all my measurements since Garmin Connect uploads broke, and it stopped working after several quick uploads (about 1 every 5-10 seconds). It would complain about wrong username or password, but after several hours it started to work again without any change from my side.
I took the opportunity to update to the latest ANTlib library from here: https://github.com/ant-wireless/ANT-Android-SDKs/tree/master/ANT_Android_SDK/API

**Comment by rbaret** [comment]
Thank you very much Daniel ! Great job !
Do you plan on making a new release that we can download like the v3.17 ?
Your app is still the best around ! 
Also thank you for having released the source code so that people can participate 😍

**Comment by danips** [comment]
I am working on creating a release. But I still have to fix an issue I am getting when generating the APK.

**Comment by Lay3r3ight** [comment]
Thanks for fixing this app Daniel, I appreciate that!

**Comment by danips** [comment]
> Also, I would kindly ask if you could remove the licence check because its not longer possible to buy the app in the play store. At the moment, the app is only working in demo mode on my wifes S20+. But she is using the playstore version 3.17, not sure if the github version 3.17 is diffent.

You can try installing the APK in https://github.com/danips/ANTWeightScaleDisplay/releases/tag/v3.18 That has no licence checking at all. I am still trying to figure out how to generate an app to upload to Google Play. I am having conflicts between the HTTP Client the upload code uses and Android's classes.

**Comment by rbaret** [comment]
I have uninstalled, cleaned data and reinstalled the new version. I still get the Incorrect username/password error when both are correct (tried to login in the browser)
